import Head from "next/head";
import Categories from "../components/Categories";
import PostWidget from "../components/PostWidget";
import PostCard from "../components/PostCard";
import { getPosts } from "../lib/hygraph";
import FilterCategories from "../components/FilterCategories";

export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-1 md:grid-cols-12">
        <div className="md:col-span-8 divide-y col-span-1 px-10 my-5 min-h-screen border-b space-y-5 md:border-b-0 md:border-r">
          <FilterCategories />
          {posts.map((post, index) => (
            <PostCard key={index} post={post.node} />
          ))}
        </div>
        <div className="md:col-span-4 col-span-1 p-5 h-screen ">
          <div className="md:sticky relative top-8  h-screen">
            <PostWidget />
            <div className="hidden md:inline">
              <Categories />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const posts = (await getPosts()) || [];

  return {
    props: {
      posts,
    },
  };
}
